# Configuration for welcome - https://github.com/behaviorbot/welcome
newIssueWelcomeComment: |
  ðŸ’– Thanks for opening this issue. ðŸ’–

  A Codinasion team member should be by to give feedback soon. In the meantime, please check out the [contributing guidelines](https://github.com/codinasion/codinasion-dsa/blob/master/CONTRIBUTING.md).
firstPRMergeComment: |
  Congrats on merging your first pull request! ðŸŽ‰ðŸŽ‰ðŸŽ‰
